- hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Update and upgrade apt packages
      apt: 
        update_cache: yes
        upgrade: yes

    - import_tasks: tasks/snap.yml
    - import_tasks: tasks/zsh.yml

    - import_tasks: tasks/chromium.yml
    - import_tasks: tasks/curl.yml
    - import_tasks: tasks/firacode.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/nvm-and-node.yml
    - import_tasks: tasks/postman.yml
    - import_tasks: tasks/slack.yml
    - import_tasks: tasks/ssh-key.yml
    - import_tasks: tasks/tig.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/virtual-box-guest.yml
    - import_tasks: tasks/visual-studio-code.yml