- name: Check if virtualbox
  shell: dmidecode  | grep -i -c VirtualBox
  register: is_virtualbox
  failed_when: is_virtualbox.rc == "2"
  changed_when: false

- name: Install build-essential
  when: is_virtualbox.rc == 0
  apt:
    name: build-essential
    state: latest

- name: Install gcc
  when: is_virtualbox.rc == 0
  apt:
    name: gcc
    state: latest

- name: Install perl
  when: is_virtualbox.rc == 0
  apt:
    name: perl
    state: latest

- name: Install dkms
  when: is_virtualbox.rc == 0
  apt:
    name: dkms
    state: latest

- name: Check if virtualbox-guest-additions is mounted
  shell: ls /cdrom | grep -i -c VBoxLinuxAdditions.run
  register: is_additions_mounted
  failed_when: is_additions_mounted.rc == "2"
  changed_when: false

- name: Install virtualbox-guest-additions
  when: is_virtualbox.rc == 0 and is_additions_mounted.rc == 0
  shell: /cdrom/autorun.sh